[telegram]
token = "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
workers = 1
admins = [1234567]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 0
api_hash = ""

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = ""
