[telegram]
token = "1439540619:AAG5dGE96RUXe94OQfpevNlMb2uRsW_PhcE"
workers = 1
admins = [853393439]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 1358970
api_hash = "57aff1848504fcde424d181d5cfee983"

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = "t.me/DamienSoukara"
issues = "Github@AmineSoukara"
channel = "DamienSoukara"
