[telegram]
token = "ABC123"
workers = 1
admins = [853393439]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 123
api_hash = "ABC123"

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = "t.me/DamienSoukara"
issues = "Github@AmineSoukara"
channel = "DamienSoukara"
